version: "3.4"
services:
  cybersecurity-fiap:
    tty: true
    image: "eduardomatoss/cybersecurity-fiap"
    stdin_open: true
    build:
      context: .
      target: "development"
    env_file: .env
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
