version: "3.4"
services:
  cybersecurity-fiap:
    tty: true
    image: "eduardomatoss/cybersecurity-fiap"
    stdin_open: true
    build:
      context: .
      target: "development"
    env_file: .env
    volumes:
      - ".:/app"
    environment:
      - ENV_FOR_DYNACONF=development
      - DATABASE_URL=cybersecurity
      - DATABASE_NAME=cybersecurity
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
    ports:
      - "8000:8000"
    networks:
      - db_nw

  cybersecurity-db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cybersecurity
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge

volumes:
  cybersecurity-db: